/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DataSchemaResponse,
  DataSurvey400,
  TimeSeriesDataRequest,
  TimeSeriesDataResponse
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DataHandler
 */
export const dataSurvey = (
    timeSeriesDataRequest: TimeSeriesDataRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TimeSeriesDataResponse>(
      {url: `/surveys/data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: timeSeriesDataRequest, signal
    },
      );
    }
  


export const getDataSurveyMutationOptions = <TError = DataSurvey400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataSurvey>>, TError,{data: TimeSeriesDataRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof dataSurvey>>, TError,{data: TimeSeriesDataRequest}, TContext> => {

const mutationKey = ['dataSurvey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dataSurvey>>, {data: TimeSeriesDataRequest}> = (props) => {
          const {data} = props ?? {};

          return  dataSurvey(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DataSurveyMutationResult = NonNullable<Awaited<ReturnType<typeof dataSurvey>>>
    export type DataSurveyMutationBody = TimeSeriesDataRequest
    export type DataSurveyMutationError = DataSurvey400

    /**
 * @summary DataHandler
 */
export const useDataSurvey = <TError = DataSurvey400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataSurvey>>, TError,{data: TimeSeriesDataRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dataSurvey>>,
        TError,
        {data: TimeSeriesDataRequest},
        TContext
      > => {

      const mutationOptions = getDataSurveyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary DataSchemaHandler
 */
export const dataSchemaSurvey = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<DataSchemaResponse>(
      {url: `/surveys/data/schema`, method: 'GET', signal
    },
      );
    }
  



export const getDataSchemaSurveyQueryKey = () => {
    return [
    `/surveys/data/schema`
    ] as const;
    }

    
export const getDataSchemaSurveyQueryOptions = <TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataSchemaSurveyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataSchemaSurvey>>> = ({ signal }) => dataSchemaSurvey(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataSchemaSurveyQueryResult = NonNullable<Awaited<ReturnType<typeof dataSchemaSurvey>>>
export type DataSchemaSurveyQueryError = unknown


export function useDataSchemaSurvey<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataSchemaSurvey>>,
          TError,
          Awaited<ReturnType<typeof dataSchemaSurvey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaSurvey<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataSchemaSurvey>>,
          TError,
          Awaited<ReturnType<typeof dataSchemaSurvey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaSurvey<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DataSchemaHandler
 */

export function useDataSchemaSurvey<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataSchemaSurveyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getDataSchemaSurveySuspenseQueryOptions = <TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataSchemaSurveyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataSchemaSurvey>>> = ({ signal }) => dataSchemaSurvey(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataSchemaSurveySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof dataSchemaSurvey>>>
export type DataSchemaSurveySuspenseQueryError = unknown


export function useDataSchemaSurveySuspense<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaSurveySuspense<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaSurveySuspense<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DataSchemaHandler
 */

export function useDataSchemaSurveySuspense<TData = Awaited<ReturnType<typeof dataSchemaSurvey>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaSurvey>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataSchemaSurveySuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




