"""extend_orgs_reports_subscriptions

Revision ID: ae39d8c18f62
Revises: a413a90e6b69
Create Date: 2026-05-07 00:18:47.527717+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.domain.reports.enums import ReportState
from app.domain.subscriptions.enums import SubscriptionPlan, SubscriptionStatus
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "ae39d8c18f62"
down_revision: str | None = "a413a90e6b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("plan", TextEnum(SubscriptionPlan), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.Text(), nullable=True),
        sa.Column("stripe_subscription_id", sa.Text(), nullable=True),
        sa.Column("state", TextEnum(SubscriptionStatus), server_default="trialing", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", name="uq_subscription_per_org"),
    )
    op.create_index(op.f("ix_subscriptions_organization_id"), "subscriptions", ["organization_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_state"), "subscriptions", ["state"], unique=False)
    op.create_table(
        "reports",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("market_value_cents", sa.Integer(), nullable=True),
        sa.Column("replacement_value_cents", sa.Integer(), nullable=True),
        sa.Column("watermarked_file_key", sa.Text(), nullable=True),
        sa.Column("released_file_key", sa.Text(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", TextEnum(ReportState), server_default="draft", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False)
    op.create_index(op.f("ix_reports_state"), "reports", ["state"], unique=False)
    op.create_index(op.f("ix_reports_survey_id"), "reports", ["survey_id"], unique=False)
    op.add_column("clients", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_clients_organization_id"), "clients", ["organization_id"], unique=False)
    op.create_foreign_key(None, "clients", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT")
    op.add_column("invoices", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False)
    op.create_foreign_key(None, "invoices", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT")
    op.add_column("organizations", sa.Column("phone", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("email", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("website", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("address_id", sa.Integer(), nullable=True))
    op.add_column("organizations", sa.Column("nams_member_number", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("sams_member_number", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("signature_block", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("report_footer", sa.Text(), nullable=True))
    op.create_index(op.f("ix_organizations_address_id"), "organizations", ["address_id"], unique=False)
    op.create_foreign_key(None, "organizations", "addresses", ["address_id"], ["id"], ondelete="SET NULL")
    op.add_column("surveys", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_surveys_organization_id"), "surveys", ["organization_id"], unique=False)
    op.create_foreign_key(None, "surveys", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT")
    op.add_column("vessels", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_vessels_organization_id"), "vessels", ["organization_id"], unique=False)
    op.create_foreign_key(None, "vessels", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vessels", type_="foreignkey")
    op.drop_index(op.f("ix_vessels_organization_id"), table_name="vessels")
    op.drop_column("vessels", "organization_id")
    op.drop_constraint(None, "surveys", type_="foreignkey")
    op.drop_index(op.f("ix_surveys_organization_id"), table_name="surveys")
    op.drop_column("surveys", "organization_id")
    op.drop_constraint(None, "organizations", type_="foreignkey")
    op.drop_index(op.f("ix_organizations_address_id"), table_name="organizations")
    op.drop_column("organizations", "report_footer")
    op.drop_column("organizations", "signature_block")
    op.drop_column("organizations", "sams_member_number")
    op.drop_column("organizations", "nams_member_number")
    op.drop_column("organizations", "address_id")
    op.drop_column("organizations", "website")
    op.drop_column("organizations", "email")
    op.drop_column("organizations", "phone")
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_column("invoices", "organization_id")
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_index(op.f("ix_clients_organization_id"), table_name="clients")
    op.drop_column("clients", "organization_id")
    op.drop_index(op.f("ix_reports_survey_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_state"), table_name="reports")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_subscriptions_state"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
