"""add_domain_models

Revision ID: a413a90e6b69
Revises: e3f4a5b6c7d8
Create Date: 2026-05-06 23:54:43.532627+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a413a90e6b69"
down_revision: str | None = "e3f4a5b6c7d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("line1", sa.Text(), nullable=False),
        sa.Column("line2", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), server_default="US", nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_templates",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("applies_to_survey_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clients",
        sa.Column("client_type", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("billing_address_id", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("claim_contact_name", sa.Text(), nullable=True),
        sa.Column("institution_name", sa.Text(), nullable=True),
        sa.Column("loan_officer_name", sa.Text(), nullable=True),
        sa.Column("brokerage_name", sa.Text(), nullable=True),
        sa.Column("agent_name", sa.Text(), nullable=True),
        sa.Column("license_number", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["billing_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_billing_address_id"), "clients", ["billing_address_id"], unique=False)
    op.create_index(op.f("ix_clients_client_type"), "clients", ["client_type"], unique=False)
    op.create_table(
        "vessels",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hin", sa.Text(), nullable=True),
        sa.Column("uscg_official_number", sa.Text(), nullable=True),
        sa.Column("state_registration_number", sa.Text(), nullable=True),
        sa.Column("builder", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("vessel_type", sa.Text(), nullable=True),
        sa.Column("propulsion_type", sa.Text(), nullable=True),
        sa.Column("rigging_type", sa.Text(), nullable=True),
        sa.Column("loa_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("beam_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("draft_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("displacement_lbs", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("fuel_capacity_gal", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("hull_material", sa.Text(), nullable=True),
        sa.Column("construction_notes", sa.Text(), nullable=True),
        sa.Column("home_port_address_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["home_port_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vessels_hin"), "vessels", ["hin"], unique=False)
    op.create_index(op.f("ix_vessels_home_port_address_id"), "vessels", ["home_port_address_id"], unique=False)
    op.create_table(
        "engines",
        sa.Column("vessel_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("make", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("serial_number", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("horsepower", sa.Integer(), nullable=True),
        sa.Column("fuel_type", sa.Text(), nullable=True),
        sa.Column("engine_type", sa.Text(), nullable=True),
        sa.Column("hours_at_survey", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vessel_id"], ["vessels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_engines_vessel_id"), "engines", ["vessel_id"], unique=False)
    op.create_table(
        "surveys",
        sa.Column("survey_type", sa.Text(), nullable=False),
        sa.Column("vessel_id", sa.Integer(), nullable=False),
        sa.Column("assigned_surveyor_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("inspection_location_address_id", sa.Integer(), nullable=True),
        sa.Column("vessel_state_at_inspection", sa.Text(), nullable=True),
        sa.Column("weather_conditions", sa.Text(), nullable=True),
        sa.Column("purpose_statement", sa.Text(), nullable=True),
        sa.Column("scope_statement", sa.Text(), nullable=True),
        sa.Column("exclusions", sa.Text(), nullable=True),
        sa.Column("limitations", sa.Text(), nullable=True),
        sa.Column("quoted_fee_cents", sa.Integer(), nullable=True),
        sa.Column("included_sea_trial", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("included_haul_out", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purchase_price_cents", sa.Integer(), nullable=True),
        sa.Column("seller_name", sa.Text(), nullable=True),
        sa.Column("policy_number", sa.Text(), nullable=True),
        sa.Column("renewal_required_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_description", sa.Text(), nullable=True),
        sa.Column("loss_type", sa.Text(), nullable=True),
        sa.Column("claim_number", sa.Text(), nullable=True),
        sa.Column("pending_insurer_approval", sa.Boolean(), nullable=True),
        sa.Column("appraisal_purpose", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.Text(), server_default="inquiry", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["assigned_surveyor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["inspection_location_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_id"], ["survey_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vessel_id"], ["vessels.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_surveys_assigned_surveyor_id"), "surveys", ["assigned_surveyor_id"], unique=False)
    op.create_index(
        op.f("ix_surveys_inspection_location_address_id"), "surveys", ["inspection_location_address_id"], unique=False
    )
    op.create_index(op.f("ix_surveys_state"), "surveys", ["state"], unique=False)
    op.create_index(op.f("ix_surveys_survey_type"), "surveys", ["survey_type"], unique=False)
    op.create_index(op.f("ix_surveys_template_id"), "surveys", ["template_id"], unique=False)
    op.create_index(op.f("ix_surveys_vessel_id"), "surveys", ["vessel_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("currency", sa.Text(), server_default="USD", nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tax_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_client_id"), "invoices", ["client_id"], unique=False)
    op.create_index(op.f("ix_invoices_survey_id"), "invoices", ["survey_id"], unique=False)
    op.create_table(
        "survey_parties",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("survey_id", "client_id", "role", name="uq_survey_party"),
    )
    op.create_index(op.f("ix_survey_parties_client_id"), "survey_parties", ["client_id"], unique=False)
    op.create_index(op.f("ix_survey_parties_survey_id"), "survey_parties", ["survey_id"], unique=False)
    op.create_table(
        "survey_response_items",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("template_node_ref", sa.Text(), nullable=True),
        sa.Column("heading_label", sa.Text(), nullable=False),
        sa.Column("category_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="not_started", nullable=False),
        sa.Column("is_finding", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_response_items_survey_id"), "survey_response_items", ["survey_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("response_item_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_area", sa.Text(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("location_on_vessel", sa.Text(), nullable=True),
        sa.Column("is_pre_existing", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["response_item_id"], ["survey_response_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_response_item_id"), "findings", ["response_item_id"], unique=False)
    op.create_index(op.f("ix_findings_survey_id"), "findings", ["survey_id"], unique=False)
    op.create_table(
        "invoice_line_items",
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_line_items_invoice_id"), "invoice_line_items", ["invoice_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("finding_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("timeframe", sa.Text(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recommendations_finding_id"), "recommendations", ["finding_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendations_finding_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_invoice_line_items_invoice_id"), table_name="invoice_line_items")
    op.drop_table("invoice_line_items")
    op.drop_index(op.f("ix_findings_survey_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_response_item_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_survey_response_items_survey_id"), table_name="survey_response_items")
    op.drop_table("survey_response_items")
    op.drop_index(op.f("ix_survey_parties_survey_id"), table_name="survey_parties")
    op.drop_index(op.f("ix_survey_parties_client_id"), table_name="survey_parties")
    op.drop_table("survey_parties")
    op.drop_index(op.f("ix_invoices_survey_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_client_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_surveys_vessel_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_template_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_survey_type"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_state"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_inspection_location_address_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_assigned_surveyor_id"), table_name="surveys")
    op.drop_table("surveys")
    op.drop_index(op.f("ix_engines_vessel_id"), table_name="engines")
    op.drop_table("engines")
    op.drop_index(op.f("ix_vessels_home_port_address_id"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_hin"), table_name="vessels")
    op.drop_table("vessels")
    op.drop_index(op.f("ix_clients_client_type"), table_name="clients")
    op.drop_index(op.f("ix_clients_billing_address_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_table("survey_templates")
    op.drop_table("addresses")
    # ### end Alembic commands ###
