"""add_soft_delete_and_template_org

Revision ID: 0404af517101
Revises: ae39d8c18f62
Create Date: 2026-05-07 01:08:23.024576+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0404af517101"
down_revision: str | None = "ae39d8c18f62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_clients_deleted_at"), "clients", ["deleted_at"], unique=False)
    op.add_column("invoices", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_invoices_deleted_at"), "invoices", ["deleted_at"], unique=False)
    op.add_column("reports", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_reports_deleted_at"), "reports", ["deleted_at"], unique=False)
    op.add_column("subscriptions", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_subscriptions_deleted_at"), "subscriptions", ["deleted_at"], unique=False)
    op.add_column("survey_templates", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.add_column("survey_templates", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_survey_templates_deleted_at"), "survey_templates", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_survey_templates_organization_id"), "survey_templates", ["organization_id"], unique=False)
    op.create_foreign_key(None, "survey_templates", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT")
    op.add_column("surveys", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_surveys_deleted_at"), "surveys", ["deleted_at"], unique=False)
    op.add_column("vessels", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_vessels_deleted_at"), "vessels", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vessels_deleted_at"), table_name="vessels")
    op.drop_column("vessels", "deleted_at")
    op.drop_index(op.f("ix_surveys_deleted_at"), table_name="surveys")
    op.drop_column("surveys", "deleted_at")
    op.drop_constraint(None, "survey_templates", type_="foreignkey")
    op.drop_index(op.f("ix_survey_templates_organization_id"), table_name="survey_templates")
    op.drop_index(op.f("ix_survey_templates_deleted_at"), table_name="survey_templates")
    op.drop_column("survey_templates", "deleted_at")
    op.drop_column("survey_templates", "organization_id")
    op.drop_index(op.f("ix_subscriptions_deleted_at"), table_name="subscriptions")
    op.drop_column("subscriptions", "deleted_at")
    op.drop_index(op.f("ix_reports_deleted_at"), table_name="reports")
    op.drop_column("reports", "deleted_at")
    op.drop_index(op.f("ix_invoices_deleted_at"), table_name="invoices")
    op.drop_column("invoices", "deleted_at")
    op.drop_index(op.f("ix_clients_deleted_at"), table_name="clients")
    op.drop_column("clients", "deleted_at")
    # ### end Alembic commands ###
